ALTER TABLE products DROP CONSTRAINT IF EXISTS products_status_check;
ALTER TABLE products ADD COLUMN brand VARCHAR(150);
ALTER TABLE products ADD COLUMN entity_purpose VARCHAR(500);
ALTER TABLE products ADD COLUMN unit_of_measure VARCHAR(60);
ALTER TABLE products ADD COLUMN monthly_required_quantity INTEGER NOT NULL DEFAULT 0 CHECK (monthly_required_quantity >= 0);
ALTER TABLE products ADD COLUMN count_pending BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE products ADD COLUMN notes TEXT;
ALTER TABLE stock_movements ADD COLUMN responsible_name VARCHAR(150);
ALTER TABLE stock_movements ADD COLUMN purpose VARCHAR(255);
ALTER TABLE stock_movements ADD COLUMN event_name VARCHAR(180);
ALTER TABLE stock_movements ADD COLUMN notes TEXT;

DELETE FROM stock_movements;
DELETE FROM products;
DELETE FROM categories;

INSERT INTO categories (name, description) VALUES
('Guias Espirituais', 'Categoria importada da planilha do Instituto'),
('Utilidades', 'Categoria importada da planilha do Instituto'),
('Magias', 'Categoria importada da planilha do Instituto'),
('Recipientes', 'Categoria importada da planilha do Instituto'),
('Especiarias', 'Categoria importada da planilha do Instituto'),
('Natural', 'Categoria importada da planilha do Instituto'),
('Medicina', 'Categoria importada da planilha do Instituto'),
('Grãos', 'Categoria importada da planilha do Instituto'),
('Alimentos', 'Categoria importada da planilha do Instituto'),
('Plantas', 'Categoria importada da planilha do Instituto'),
('Bebida', 'Categoria importada da planilha do Instituto'),
('Velas', 'Categoria importada da planilha do Instituto');

INSERT INTO products (
    name, brand, entity_purpose, unit_of_measure, category_id,
    cost_price, sale_price, quantity, minimum_stock,
    monthly_required_quantity, count_pending, status, notes
) VALUES
('Caneca de Vidro', 'Transparente', 'Encantados/Caboclos', 'Unidade', (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Maçarico Culinário', 'Sem Marca', 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Utilidades'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Água de Florida', 'Peruana Murray y Lanman', 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Magias'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Alfazema', 'Halley Original', 'Cerimônia/Casa/Comida de Santo/Presente', NULL, (SELECT id FROM categories WHERE name='Magias'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Alguidar 0', 'Barro', 'Ebó/Comida de Santo/Presentes', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Alguidar 1', 'Barro', 'Ebó/Comida de Santo/Presentes', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Alguidar 2', 'Barro', 'Ebó/Comida de Santo/Presentes', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Alguidar 3', 'Barro', 'Ebó/Comida de Santo/Presentes', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Almofadas', 'Sem Marca', 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Utilidades'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Anis Estrelado', 'Sem Marca', 'Banhos/Chás/Presentes', NULL, (SELECT id FROM categories WHERE name='Especiarias'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Areia de Praia', 'Natural', 'Comida de Santo', NULL, (SELECT id FROM categories WHERE name='Natural'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Argila', 'Preta', 'Magias', NULL, (SELECT id FROM categories WHERE name='Natural'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Ayahuasca', NULL, 'Cerimônia', NULL, (SELECT id FROM categories WHERE name='Medicina'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Bacia de Agata Branca Grande', 'Sem Marca', 'Ebó/Comida de Santo/Presentes', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Bacia de Agata Branca Médio', 'Sem Marca', 'Ebó/Comida de Santo/Presentes', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Bacia de Agata Branca Pequena', 'Sem Marca', 'Ebó/Comida de Santo/Presentes', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Bacia de Bronze', 'Sem Marca', 'Pade/Ebó/Comida de Santo/Presentes', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Banco Branco com Gaveta', 'Sem Marca', 'Sr Francisco Aldeão/Cambinda', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Banco de Madeira Redondo', 'Sem Marca', 'Entidades', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Banco de Madeira Retângular', 'Sem Marca', 'Sr João das Matas', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Bown Branco de Cerâmica Grande', 'Sem Marca', 'Comida de Santo/Presentes', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Bown Branco de Cerâmica Médio', 'Sem Marca', 'Comida de Santo/Presentes', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Búzios', 'Aberto', 'Ebó/Presentes/Firmezas', NULL, (SELECT id FROM categories WHERE name='Magias'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Cadeira de Madeira Alta', 'Sem Marca', 'Sr Meia Noite/Sra Maria Padilha/Sra Dama da Noite/Tranca Ruas', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Cadeira de Madeira Baixa', 'Sem Marca', 'Sr João das Matas', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Caneca de Agata Branca Grande', 'Sem Marca', 'Incorporação', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Canela em Pau', 'Sem Marca', 'Banhos/Chás/Presentes', NULL, (SELECT id FROM categories WHERE name='Especiarias'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Canela em Pó', 'Sem Marca', 'Banhos/Chás', NULL, (SELECT id FROM categories WHERE name='Especiarias'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Canjica Branca', 'Sem Marca', 'Comida de Santo/Ebó/Presente', NULL, (SELECT id FROM categories WHERE name='Grãos'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Carvão de Côco', 'Sem Marca', 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Utilidades'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Castiçal', 'Sem Marca', 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Utilidades'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Castiçal com Cúpula de Vidro', 'Sem Marca', 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Utilidades'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Cesto de Palha Grande', 'Sem Marca', 'Comida de Santo/Presentes', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Cesto de Palha Médio', 'Sem Marca', 'Comida de Santo/Presentes', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Cesto de Palha Pequeno', 'Sem Marca', 'Comida de Santo/Presentes', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Charuto', 'Titan/Dona Flor', 'Sr Meia Noite', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Charuto', 'Talvis', 'Exú/Boiadeiro', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Charuto', 'Bem Bom', 'Ebó', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Cigarilha', 'Gold', 'Sra Maria Padilha', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Cigarro', 'Wiston Red', 'Pade/Pomba Gira', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Cigarro de Palha', 'Sem Marca', 'Mestre Zé Pilintra/Malandros/Boiadeiros/Pretos Velhos/ Sr Pescador/ Sr João Manato', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Coité', 'Côco', 'Malunguinho/Bebida Festejo', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Copo Americano', 'Vidro', 'Mestre Zé Pilintra', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Copo de Whisky', 'Cristal', 'Sr Meia Noite', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Copo Dose', 'Cristal', 'Mestre Zé Pilintra', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Cravo', 'Sem Marca', 'Pade/Banhos/Chás/Presentes', NULL, (SELECT id FROM categories WHERE name='Especiarias'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Cumbuca', 'Côco', 'Comida Festejo', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Defumador de Barro', 'Sem Marca', 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Utilidades'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Defumador de Metal', 'Sem Marca', 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Utilidades'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Dendê', 'Sem Marca', 'Pade/Comida de Santo/Ebó/Presente', 'Litro', (SELECT id FROM categories WHERE name='Alimentos'), 0, 0, 3, 5, 5, false, 'SALDO_NEGATIVO', NULL),
('Efun', 'Rezado', 'Magias', NULL, (SELECT id FROM categories WHERE name='Magias'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Ervas Defumação', 'Variadas', 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Magias'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Ervilha', 'Sem Marca', 'Comida de Santo/Ebó/Presente', NULL, (SELECT id FROM categories WHERE name='Grãos'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Esteira de Palha', 'Sem Marca', 'Cerimônia/Casa/Comida de Santo/Presente', NULL, (SELECT id FROM categories WHERE name='Utilidades'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Farinha de Acarajé', 'Sem Marca', 'Comida de Santo/Ebó/Presente', 'Kilo', (SELECT id FROM categories WHERE name='Alimentos'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Farinha de Mandioca Grossa', 'Sem Marca', 'Pade/Comida de Santo/Ebó/Presente', 'Kilo', (SELECT id FROM categories WHERE name='Alimentos'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Farinha de Milho Amarela', 'Sem Marca', 'Comida de Santo/Ebó/Presente', 'Kilo', (SELECT id FROM categories WHERE name='Alimentos'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Farinha de Milho Branca', 'Sem Marca', 'Comida de Santo/Ebó/Presente', 'Kilo', (SELECT id FROM categories WHERE name='Alimentos'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Feijão Fradinho', 'Sem Marca', 'Comida de Santo/Ebó/Presente', NULL, (SELECT id FROM categories WHERE name='Grãos'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Feijão Preto', 'Sem Marca', 'Comida de Santo/Ebó/Presente', NULL, (SELECT id FROM categories WHERE name='Grãos'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Flor', 'Rosa Vermelha', 'Pade', NULL, (SELECT id FROM categories WHERE name='Plantas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Fogareiro Defumação', 'Sem Marca', 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Utilidades'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Fósforo', 'Fiat Lux', 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Utilidades'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Gamela Grande', 'Sem Marca', 'Comida de Santo', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Gamela Média', 'Sem Marca', 'Comida de Santo', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Gás Butano', 'Sem Marca', 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Utilidades'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Gin', 'Contini', 'Lonan', NULL, (SELECT id FROM categories WHERE name='Bebida'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Groselha', 'Sem Marca', 'Pade', NULL, (SELECT id FROM categories WHERE name='Bebida'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Incenso Massala', 'Boa Qualidade', 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Magias'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Jarra de Vidro', 'Sem Marca', 'Cerimônia/Jogos/Decantar Água/Entidades', NULL, (SELECT id FROM categories WHERE name='Utilidades'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Lavanda', 'Halley Original', 'Cerimônia/Casa/Comida de Santo/Presente', NULL, (SELECT id FROM categories WHERE name='Magias'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Lentilha', 'Sem Marca', 'Comida de Santo/Ebó/Presente', NULL, (SELECT id FROM categories WHERE name='Grãos'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Maça', 'Sem Marca', 'Pade/Presentes', NULL, (SELECT id FROM categories WHERE name='Alimentos'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Maçarico Médio', 'Sem Marca', 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Utilidades'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Mel', 'Sem Marca, natural', 'Pade/Comida de Santo/Ebó/Presente', NULL, (SELECT id FROM categories WHERE name='Alimentos'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Milho de Galinha', 'Sem Marca', 'Comida de Santo/Ebó/Presente', NULL, (SELECT id FROM categories WHERE name='Grãos'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Milho de Pipoca', 'Sem Marca', 'Comida de Santo/Ebó/Presente', NULL, (SELECT id FROM categories WHERE name='Grãos'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Pemba', 'Sem Marca', 'Magias', NULL, (SELECT id FROM categories WHERE name='Magias'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Peneira de Palha', 'Sem Marca', 'Comida de Santo/Jogos', NULL, (SELECT id FROM categories WHERE name='Utilidades'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Pimenta Vermelha', 'Dedo de Moça', 'Pade/Presentes', NULL, (SELECT id FROM categories WHERE name='Alimentos'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Pinga', 'Pitu', 'Malunguinho', NULL, (SELECT id FROM categories WHERE name='Bebida'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Pinga', '51', 'Pade', NULL, (SELECT id FROM categories WHERE name='Bebida'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Pinga', 'Artesanal', 'Mestre Zé Pilintra', NULL, (SELECT id FROM categories WHERE name='Bebida'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Pó Bronze', 'Sem Marca', 'Magias', NULL, (SELECT id FROM categories WHERE name='Magias'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Pó Dourado', 'Sem Marca', 'Magias', NULL, (SELECT id FROM categories WHERE name='Magias'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Pó Prata', 'Sem Marca', 'Magias', NULL, (SELECT id FROM categories WHERE name='Magias'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Prato Branco Grande', 'Sem Marca', 'Comida de Santo/Presentes/Assentamento', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Prato Branco Pequeno', 'Sem Marca', 'Comida de Santo/Presentes/Assentamento/Oráculo', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Prato de Marajoara', 'Marrom', 'Sr João Das Matas/Jogos', NULL, (SELECT id FROM categories WHERE name='Utilidades'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Prato Preto Pequeno', 'Sem Marca', 'Sr Meia Noite', NULL, (SELECT id FROM categories WHERE name='Recipientes'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Rapé Aroeira', 'Por do Sol', 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Medicina'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Rapé Mulungu', 'Por do Sol', 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Medicina'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Rapé Tsuno', 'Por do Sol', 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Medicina'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Resina Defumação', NULL, 'Cerimônia/Casa', NULL, (SELECT id FROM categories WHERE name='Utilidades'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Sabão da Costa', 'Rezado', 'Pade/Comida de Santo/Presente', NULL, (SELECT id FROM categories WHERE name='Magias'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Sananga', NULL, 'Cerimônia', NULL, (SELECT id FROM categories WHERE name='Medicina'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Semente de Girrasol', 'Sem Marca', 'Comida de Santo/Ebó/Presente/Banho', NULL, (SELECT id FROM categories WHERE name='Grãos'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Tabaco', 'Irlandez', 'Sr João das Matas', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Tabaco', 'Artesanal', 'Mestre Zé Pilintra/Entidades', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Taça de Vidro', 'Vermelha', 'Pomba gira', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Taça de Vidro', 'Transparente', 'Jogos/Oráculo', NULL, (SELECT id FROM categories WHERE name='Guias Espirituais'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela 7 Dias Amarela Mel', '7 Luz', 'Ciganos', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela 7 Dias Azul e Preta', '7 Luz', 'Sr Meia Noite', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela 7 Dias Branca', '7 Luz', 'Orixás/Nkisi/Kusynakan/Sr Pescador/Sr 7 Encruzilhadas', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela 7 Dias Branca e Preta', '7 Luz', 'Pretos Velhos', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela 7 Dias Branca e Vermelha', '7 Luz', 'Mestre Zé Pilintra', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela 7 Dias Verde', '7 Luz', 'Malunguinho/Sr João das Matas', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela 7 Dias Vermelha', '7 Luz', 'Sra Maria Padilha', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela 7 Dias Vermelha e Preta', '7 Luz', 'Sr Tiriri/Sr 7 Porteiras', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela Palito Amarela', '7 Luz', 'Sr João das Matas/Jurema/Ciganos/Kafioto Bigorninha', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela Palito Azul Escuro', '7 Luz', 'Kafioto Bigorninha', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela Palito Branca', '7 Luz', 'Banho/Pade/Comida de Santo/Presente/Jogos/Oráculo/Sr Tranca Ruas', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela Palito Branca e Preta', '7 Luz', 'Pretos Velhos', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela Palito Branca e Vermelha', '7 Luz', 'Mestre Zé Pilintra/Mestra Maria Navalha', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela Palito Preta', '7 Luz', 'Sr Meia Noite/Sr Tata Caveira/Sr Exu Gato', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela Palito Preta e Azul', '7 Luz', 'Sr Meia Noite', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela Palito Roxa', '7 Luz', 'Sra Rosa Caveira', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela Palito Verde', '7 Luz', 'Sr João das Matas/Kusynakan/Caboclos/Boiadeiros', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela Palito Vermelha', '7 Luz', 'Ciganos/Sra Maria Padilha/Pomba Giras', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vela Palito Vermelha e Preta', '7 Luz', 'Sra Dama da Noite', NULL, (SELECT id FROM categories WHERE name='Velas'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Vinho', 'Chalise', 'Ciganos/Padilha', NULL, (SELECT id FROM categories WHERE name='Bebida'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Wagi', 'Sunshine Ultramarine Blue', 'Magias/Jogo/Comida de Santo/Presente', NULL, (SELECT id FROM categories WHERE name='Magias'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL),
('Whisky', 'Jack Daniels', 'Exu', 'Litro', (SELECT id FROM categories WHERE name='Bebida'), 0, 0, 0, 0, 0, true, 'PENDENTE_CONTAGEM', NULL);

ALTER TABLE products ADD CONSTRAINT products_status_check
    CHECK (status IN ('NORMAL','SALDO_NEGATIVO','PENDENTE_CONTAGEM','NECESSIDADE_REPOSICAO'));
CREATE INDEX idx_products_count_pending ON products(count_pending);
