import { CommonModule } from '@angular/common';
import { ChangeDetectorRef,Component,OnInit } from '@angular/core';
import { FormBuilder,ReactiveFormsModule,Validators } from '@angular/forms';
import { ActivatedRoute,Router,RouterLink } from '@angular/router';
import { forkJoin,of } from 'rxjs';
import { Category } from '../../core/models/category.model';
import { ProductPayload } from '../../core/models/product.model';
import { Supplier } from '../../core/models/supplier.model';
import { CategoryService } from '../../core/services/category.service';
import { ProductService } from '../../core/services/product.service';
import { SupplierService } from '../../core/services/supplier.service';
@Component({selector:'app-product-form',standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterLink],templateUrl:'./product-form.component.html',styleUrl:'./product-form.component.css'})
export class ProductFormComponent implements OnInit{categories:Category[]=[];suppliers:Supplier[]=[];saving=false;loading=true;error='';readonly productId:number|null;readonly form=this.fb.group({name:['',[Validators.required,Validators.maxLength(150)]],barcode:[''],categoryId:[null as number|null,Validators.required],supplierId:[null as number|null],costPrice:[0,[Validators.required,Validators.min(0)]],salePrice:[0,[Validators.required,Validators.min(0)]],quantity:[0,[Validators.required,Validators.min(0)]],minimumStock:[0,[Validators.required,Validators.min(0)]],expirationDate:['']});constructor(private readonly fb:FormBuilder,private readonly products:ProductService,private readonly categoriesService:CategoryService,private readonly suppliersService:SupplierService,private readonly route:ActivatedRoute,private readonly router:Router,private readonly cdr:ChangeDetectorRef){const id=route.snapshot.paramMap.get('id');this.productId=id?Number(id):null;}get editing():boolean{return this.productId!==null;}ngOnInit():void{forkJoin({categories:this.categoriesService.list(),suppliers:this.suppliersService.list(),product:this.productId===null?of(null):this.products.get(this.productId)}).subscribe({next:data=>{this.categories=data.categories;this.suppliers=data.suppliers;if(data.product)this.form.patchValue({name:data.product.name,barcode:data.product.barcode||'',categoryId:data.product.categoryId,supplierId:data.product.supplierId,costPrice:data.product.costPrice,salePrice:data.product.salePrice,quantity:data.product.quantity,minimumStock:data.product.minimumStock,expirationDate:data.product.expirationDate||''});this.loading=false;this.cdr.markForCheck();},error:()=>{this.error='Não foi possível carregar os dados do produto.';this.loading=false;this.cdr.markForCheck();}});}save():void{if(this.form.invalid){this.form.markAllAsTouched();return;}const v=this.form.getRawValue();const payload:ProductPayload={name:v.name!.trim(),barcode:v.barcode?.trim()||null,categoryId:Number(v.categoryId),supplierId:v.supplierId===null?null:Number(v.supplierId),costPrice:Number(v.costPrice),salePrice:Number(v.salePrice),quantity:Number(v.quantity),minimumStock:Number(v.minimumStock),expirationDate:v.expirationDate||null};this.saving=true;this.error='';const request=this.productId===null?this.products.create(payload):this.products.update(this.productId,payload);request.subscribe({next:()=>void this.router.navigate(['/produtos'],{queryParams:{success:this.editing?'Produto atualizado com sucesso.':'Produto cadastrado com sucesso.'}}),error:r=>{this.error=r.error?.message||'Não foi possível salvar o produto.';this.saving=false;this.cdr.markForCheck();}});}invalid(field:string):boolean{const c=this.form.get(field);return !!c&&c.invalid&&c.touched;}}
