package com.estoqueinteligente.stockmovement;

import java.math.BigDecimal;
import java.time.Instant;

public class StockMovementResponse {
    private final Long id; private final Long productId; private final String productName; private final StockMovementType movementType;
    private final Integer quantity; private final Integer previousQuantity; private final Integer newQuantity; private final BigDecimal unitValue,totalValue; private final Long entryTypeId,exitTypeId; private final String entryTypeName,exitTypeName,reason,responsibleName,purpose,eventName,notes; private final Instant createdAt;
    public StockMovementResponse(Long id,Long productId,String productName,StockMovementType movementType,Integer quantity,Integer previousQuantity,Integer newQuantity,BigDecimal unitValue,BigDecimal totalValue,Long entryTypeId,String entryTypeName,Long exitTypeId,String exitTypeName,String reason,String responsibleName,String purpose,String eventName,String notes,Instant createdAt){this.id=id;this.productId=productId;this.productName=productName;this.movementType=movementType;this.quantity=quantity;this.previousQuantity=previousQuantity;this.newQuantity=newQuantity;this.unitValue=unitValue;this.totalValue=totalValue;this.entryTypeId=entryTypeId;this.entryTypeName=entryTypeName;this.exitTypeId=exitTypeId;this.exitTypeName=exitTypeName;this.reason=reason;this.responsibleName=responsibleName;this.purpose=purpose;this.eventName=eventName;this.notes=notes;this.createdAt=createdAt;}
    public static StockMovementResponse from(StockMovement m){return new StockMovementResponse(m.getId(),m.getProduct().getId(),m.getProduct().getName(),m.getMovementType(),m.getQuantity(),m.getPreviousQuantity(),m.getNewQuantity(),m.getUnitValue(),m.getTotalValue(),m.getEntryType()==null?null:m.getEntryType().getId(),m.getEntryType()==null?null:m.getEntryType().getName(),m.getExitType()==null?null:m.getExitType().getId(),m.getExitType()==null?null:m.getExitType().getName(),m.getReason(),m.getResponsibleName(),m.getPurpose(),m.getEventName(),m.getNotes(),m.getCreatedAt());}
    public Long getId(){return id;} public Long getProductId(){return productId;} public String getProductName(){return productName;} public StockMovementType getMovementType(){return movementType;} public Integer getQuantity(){return quantity;} public Integer getPreviousQuantity(){return previousQuantity;} public Integer getNewQuantity(){return newQuantity;} public String getReason(){return reason;} public Instant getCreatedAt(){return createdAt;}
    public BigDecimal getUnitValue(){return unitValue;} public BigDecimal getTotalValue(){return totalValue;} public Long getEntryTypeId(){return entryTypeId;} public String getEntryTypeName(){return entryTypeName;} public Long getExitTypeId(){return exitTypeId;} public String getExitTypeName(){return exitTypeName;} public String getResponsibleName(){return responsibleName;} public String getPurpose(){return purpose;} public String getEventName(){return eventName;} public String getNotes(){return notes;}
}
