import{CommonModule}from'@angular/common';import{ChangeDetectorRef,Component,OnInit}from'@angular/core';import{FormBuilder,ReactiveFormsModule,Validators}from'@angular/forms';import{ActivatedRoute,Router,RouterLink}from'@angular/router';import{finalize,forkJoin,timeout}from'rxjs';import{ExitType}from'../../core/models/exit-type.model';import{Product}from'../../core/models/product.model';import{StockMovementPayload,StockMovementType}from'../../core/models/stock-movement.model';import{ExitTypeService}from'../../core/services/exit-type.service';import{ProductService}from'../../core/services/product.service';import{StockMovementService}from'../../core/services/stock-movement.service';
@Component({selector:'app-stock-movement-form',standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterLink],templateUrl:'./stock-movement-form.component.html',styleUrl:'./stock-movement-form.component.css'})
export class StockMovementFormComponent implements OnInit{products:Product[]=[];exitTypes:ExitType[]=[];saving=false;loading=true;error='';readonly types:StockMovementType[]=['ENTRADA','SAIDA','AJUSTE'];readonly form=this.fb.group({productId:[null as number|null,Validators.required],movementType:[null as StockMovementType|null,Validators.required],quantity:[null as number|null,[Validators.required,Validators.min(0)]],unitValue:[null as number|null,[Validators.min(0)]],exitTypeId:[null as number|null],reason:['',[Validators.maxLength(255)]],responsibleName:[''],purpose:[''],eventName:[''],notes:['']});constructor(private fb:FormBuilder,private productsService:ProductService,private exitTypeService:ExitTypeService,private movements:StockMovementService,private route:ActivatedRoute,private router:Router,private cdr:ChangeDetectorRef){}
ngOnInit():void{forkJoin({products:this.productsService.list(),exitTypes:this.exitTypeService.list(true)}).pipe(timeout(8000),finalize(()=>{this.loading=false;this.cdr.markForCheck();})).subscribe({next:d=>{this.products=d.products;this.exitTypes=d.exitTypes;const selected=this.route.snapshot.queryParamMap.get('productId');if(selected)this.form.patchValue({productId:Number(selected)});},error:()=>this.error='NÃ£o foi possÃ­vel carregar os dados. Confirme se o backend estÃ¡ ativo em /api.'});}
get selectedProduct():Product|undefined{return this.products.find(p=>p.id===Number(this.form.value.productId));}
get isAdjustment():boolean{return this.form.value.movementType==='AJUSTE';}
get isExit():boolean{return this.form.value.movementType==='SAIDA';}
get suggestedUnitValue():number{const p=this.selectedProduct;if(!p)return 0;if(this.form.value.movementType==='ENTRADA')return p.purchaseValue||0;if(this.form.value.movementType==='SAIDA')return p.averageCost||0;if(this.form.value.movementType==='AJUSTE')return Number(this.form.value.quantity||0)>p.currentQuantity?(p.purchaseValue||0):(p.averageCost||0);return 0;}
get calculatedTotal():number{return Number(this.form.value.quantity||0)*Number(this.form.value.unitValue??this.suggestedUnitValue);}
save():void{if(this.form.invalid){this.form.markAllAsTouched();return;}const value=this.form.getRawValue();const payload:StockMovementPayload={productId:Number(value.productId),movementType:value.movementType!,quantity:Number(value.quantity),unitValue:value.unitValue===null?null:Number(value.unitValue),entryTypeId:null,exitTypeId:value.movementType==='SAIDA'&&value.exitTypeId?Number(value.exitTypeId):null,reason:value.reason?.trim()||null,responsibleName:value.responsibleName?.trim()||null,purpose:value.purpose?.trim()||null,eventName:value.eventName?.trim()||null,notes:value.notes?.trim()||null};this.saving=true;this.error='';this.movements.create(payload).subscribe({next:()=>void this.router.navigate(['/movimentacoes'],{queryParams:{success:'MovimentaÃ§Ã£o registrada e estoque atualizado.'}}),error:r=>{this.error=r.error?.message||'NÃ£o foi possÃ­vel registrar a movimentaÃ§Ã£o.';this.saving=false;this.cdr.markForCheck();}});}
invalid(field:string):boolean{const c=this.form.get(field);return!!c&&c.invalid&&c.touched;}
typeLabel(type:StockMovementType):string{return{ENTRADA:'Entrada',SAIDA:'SaÃ­da',AJUSTE:'Ajuste'}[type];}}

